// TypeScript Declaration (.d.ts) Generator for PlainScript.
// Analyzes AST records, functions, variables, and exports to emit idiomatic .d.ts files.

function inferTypeFromLiteral(node) {
  if (!node) return 'any';
  switch (node.type) {
    case 'StringLiteral':
    case 'TemplateLiteral':
      return 'string';
    case 'NumberLiteral':
      return 'number';
    case 'BigIntLiteral':
      return 'bigint';
    case 'BooleanLiteral':
      return 'boolean';
    case 'ArrayLiteral':
    case 'ListLiteral':
      if (node.elements && node.elements.length > 0) {
        const elemType = inferTypeFromLiteral(node.elements[0]);
        return `${elemType}[]`;
      }
      return 'any[]';
    case 'ObjectLiteral':
    case 'RecordLiteral':
      return 'Record<string, any>';
    case 'NullLiteral':
      return 'null';
    case 'UndefinedLiteral':
      return 'undefined';
    default:
      return 'any';
  }
}

function mapTypeName(name) {
  if (!name) return 'any';
  const lower = String(name).toLowerCase();
  if (lower === 'string' || lower === 'text') return 'string';
  if (lower === 'number' || lower === 'int' || lower === 'float') return 'number';
  if (lower === 'boolean' || lower === 'bool') return 'boolean';
  if (lower === 'list' || lower === 'array') return 'any[]';
  if (lower === 'record' || lower === 'object') return 'Record<string, any>';
  if (lower === 'function') return '(...args: any[]) => any';
  return name;
}

function generateTypeDeclarations(ast, options = {}) {
  const lines = [
    '// Auto-generated TypeScript definitions for PlainScript source.',
    '// Generated by PlainScript Compiler.',
    '',
  ];

  const recordKinds = new Map();

  // 1. Pass: Collect Record Kinds
  for (const node of ast.body) {
    if (node.type === 'DefineKindStatement') {
      const kindName = node.name;
      const fields = [];
      if (Array.isArray(node.fields)) {
        for (const f of node.fields) {
          const fName = f.key || f.name;
          const fType = inferTypeFromLiteral(f.value || f.default);
          fields.push(`  ${fName}: ${fType};`);
        }
      }
      recordKinds.set(kindName, fields);
    }
  }

  // 2. Pass: Emit Declarations
  for (const node of ast.body) {
    if (node.type === 'DefineKindStatement') {
      const kindName = node.name;
      const fields = recordKinds.get(kindName) || [];
      lines.push(`export interface ${kindName} {`);
      lines.push(fields.length > 0 ? fields.join('\n') : '  [key: string]: any;');
      lines.push('}');
      lines.push(`export declare function create${kindName}(props?: Partial<${kindName}>): ${kindName};`);
      lines.push('');
    }

    if (node.type === 'FunctionDeclaration') {
      const fnName = node.name;
      const params = (node.params || []).map((p) => {
        if (typeof p === 'string') return `${p}: any`;
        const pName = p.name || 'arg';
        const defaultVal = p.defaultValue || p.default;
        let pType = 'any';
        if (defaultVal) pType = inferTypeFromLiteral(defaultVal);
        const optional = defaultVal ? '?' : '';
        return `${pName}${optional}: ${pType}`;
      });
      lines.push(`export declare function ${fnName}(${params.join(', ')}): any;`);
    }

    if (node.type === 'RememberStatement' || node.type === 'LetStatement') {
      const vName = node.name;
      const vType = inferTypeFromLiteral(node.value);
      lines.push(`export declare let ${vName}: ${vType};`);
    }

    if (node.type === 'ClassDeclaration') {
      const className = node.name;
      const superClause = node.superClass ? ` extends ${node.superClass.name || 'any'}` : '';
      lines.push(`export declare class ${className}${superClause} {`);
      lines.push('  constructor(...args: any[]);');
      lines.push('}');
      lines.push('');
    }
  }

  return lines.join('\n');
}

module.exports = { generateTypeDeclarations, inferTypeFromLiteral, mapTypeName };
